// Some action
export const SOME_ACTION = 'SOME_ACTION';

// Login
export const VERIFY_AUTH = 'VERIFY_AUTH';
export const VERIFY_AUTH_SUCCESS = 'VERIFY_AUTH_SUCCESS';
export const VERIFY_AUTH_FAILURE = 'VERIFY_AUTH_FAILURE';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const GET_SESSION = 'GET_SESSION';
export const DELETE_SESSION = 'DELETE_SESSION';

// Profile
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const CLEAR_PROFILE_ERROR = 'CLEAR_PROFILE_ERROR';
export const GET_REPOS = 'GET_REPOS';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_REPOS_FAILURE = 'GET_REPOS_FAILURE';

// Repo
export const GET_COMMITS = 'GET_COMMITS';
export const GET_COMMITS_SUCCESS = 'GET_COMMITS_SUCCESS';
export const GET_COMMITS_FAILURE = 'GET_COMMITS_FAILURE';
